import { configDotenv } from "dotenv";
import mongoose from "mongoose";
import User from "../models/User.js"; // Adjust path if needed
import bcrypt from "bcryptjs";

configDotenv();

function getRandomAmount(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
const sampleBios = [
  "Full stack developer and open source enthusiast.",
  "Aspiring entrepreneur passionate about social impact.",
  "Music lover, animal friend, and JavaScript coder.",
  "Community volunteer and tech blogger.",
  "Chasing dreams in code and coffee.",
  "AI explorer. Building cool stuff, one project at a time.",
  "Hackathon addict and UX/UI enthusiast.",
  "Nature lover and Startup Club regular.",
  "Designing for change—one pixel at a time.",
  "Keen reader, keen coder, keen learner.",
];

const users = [
  {
    name: "Priya S.",
    email: "priya@mail.com",
    password: "hashedpassword1",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[0],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Rahul Mehra",
    email: "rahul.mehra@mail.com",
    password: "hashedpassword2",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[1],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Aditi Kapoor",
    email: "aditi.kapoor@mail.com",
    password: "hashedpassword3",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[2],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Anuj Sharma",
    email: "anuj.sharma@mail.com",
    password: "hashedpassword4",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[3],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Shivansh Anand",
    email: "shivansh.anand@mail.com",
    password: "hashedpassword5",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[4],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Tanvi Arora",
    email: "tanvi.arora@mail.com",
    password: "hashedpassword6",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[5],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Neha Bansal",
    email: "neha.bansal@mail.com",
    password: "hashedpassword7",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[6],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Karan Sethi",
    email: "karan.sethi@mail.com",
    password: "hashedpassword8",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[7],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Soham Bhatt",
    email: "soham.bhatt@mail.com",
    password: "hashedpassword9",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[8],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Rhea Chopra",
    email: "rhea.chopra@mail.com",
    password: "hashedpassword10",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: sampleBios[9],
    socials: {
      linkedin: "",
      twitter: "",
      instagram: "",
    },
    badges: [],
  },
  {
    name: "Mehul Jain",
    email: "mehul.jain@mail.com",
    password: "hashedpassword11",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Finance enthusiast and marathon runner.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Sneha Iyer",
    email: "sneha.iyer@mail.com",
    password: "hashedpassword12",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Open source contributor and painting lover.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Aarav Patel",
    email: "aarav.patel@mail.com",
    password: "hashedpassword13",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Computer science major, hackathon champion.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Ishita Rao",
    email: "ishita.rao@mail.com",
    password: "hashedpassword14",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Aspiring UI/UX designer and food explorer.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Mihir Verma",
    email: "mihir.verma@mail.com",
    password: "hashedpassword15",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Android developer and chess enthusiast.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Esha Gill",
    email: "esha.gill@mail.com",
    password: "hashedpassword16",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Bookworm, podcaster, and friendly mentor.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Dev Tyagi",
    email: "dev.tyagi@mail.com",
    password: "hashedpassword17",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Agile evangelist, mountain trekker.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Riya Malhotra",
    email: "riya.malhotra@mail.com",
    password: "hashedpassword18",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Designs with heart, dances with passion.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Siddharth Sen",
    email: "siddharth.sen@mail.com",
    password: "hashedpassword19",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Front-end wizard who loves cricket.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Anushka Joshi",
    email: "anushka.joshi@mail.com",
    password: "hashedpassword20",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Singing, social work, and science podcasts.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Aman Kumar",
    email: "aman.kumar@mail.com",
    password: "hashedpassword21",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Photography lover, passionate about startups.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Simran Pal",
    email: "simran.pal@mail.com",
    password: "hashedpassword22",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Artist, poet and campus eco club member.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Harsh Tandon",
    email: "harsh.tandon@mail.com",
    password: "hashedpassword23",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Web developer and avid cyclist.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Avantika Das",
    email: "avantika.das@mail.com",
    password: "hashedpassword24",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Mathematics geek, loves modern dance.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Kabir Singh",
    email: "kabir.singh@mail.com",
    password: "hashedpassword25",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Robotics club lead, travels for coffee.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Divya Pillai",
    email: "divya.pillai@mail.com",
    password: "hashedpassword26",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Writes code, reads poetry, loves animals.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Vikram Chauhan",
    email: "vikram.chauhan@mail.com",
    password: "hashedpassword27",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "History buff and digital product manager.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Aarya Deshmukh",
    email: "aarya.deshmukh@mail.com",
    password: "hashedpassword28",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Design hackathons and classical music keep me going.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Pooja Bhatt",
    email: "pooja.bhatt@mail.com",
    password: "hashedpassword29",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Painter, leader and computer science major.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Yash Roy",
    email: "yash.roy@mail.com",
    password: "hashedpassword30",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Chess player and web-app builder.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Manvi Gupta",
    email: "manvi.gupta@mail.com",
    password: "hashedpassword31",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Community services volunteer and foodie.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Sagar Puri",
    email: "sagar.puri@mail.com",
    password: "hashedpassword32",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Machine learning enthusiast and travel blogger.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Roshni Sharma",
    email: "roshni.sharma@mail.com",
    password: "hashedpassword33",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Social media strategist and gym lover.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Dhruv Bhatia",
    email: "dhruv.bhatia@mail.com",
    password: "hashedpassword34",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Startup events and late-night coding addict.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Payal Nanda",
    email: "payal.nanda@mail.com",
    password: "hashedpassword35",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Classic literature and open-mic poetry.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Arnav Singh",
    email: "arnav.singh@mail.com",
    password: "hashedpassword36",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Sports captain and part-time coder.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Meera Sood",
    email: "meera.sood@mail.com",
    password: "hashedpassword37",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Writer, podcast host and dreamer.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Parth Ghosh",
    email: "parth.ghosh@mail.com",
    password: "hashedpassword38",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Competitive programmer and guitarist.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Swati Roy",
    email: "swati.roy@mail.com",
    password: "hashedpassword39",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Swimmer, dancer, and fundraising volunteer.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Rajveer Rana",
    email: "rajveer.rana@mail.com",
    password: "hashedpassword40",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Event organizer and finance geek.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Muskan Malhotra",
    email: "muskan.malhotra@mail.com",
    password: "hashedpassword41",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Singer by heart, coder by profession.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Pranay Kohli",
    email: "pranay.kohli@mail.com",
    password: "hashedpassword42",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Keen on AI, loves video editing.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Nitya Sethi",
    email: "nitya.sethi@mail.com",
    password: "hashedpassword43",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Baker, anime fan, tech club executive.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Arjun Bhalla",
    email: "arjun.bhalla@mail.com",
    password: "hashedpassword44",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Biohacker and startup founder in progress.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Geetika Jain",
    email: "geetika.jain@mail.com",
    password: "hashedpassword45",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Robotics volunteer and artist.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Jatin Grover",
    email: "jatin.grover@mail.com",
    password: "hashedpassword46",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Cricket buff and community tutor.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Bhavya Mahajan",
    email: "bhavya.mahajan@mail.com",
    password: "hashedpassword47",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Photography, robotics, and mountain trekking.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Anvi Saxena",
    email: "anvi.saxena@mail.com",
    password: "hashedpassword48",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Product geek, part-time singer.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Dhriti Yadav",
    email: "dhriti.yadav@mail.com",
    password: "hashedpassword49",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "Writes for campus magazine; loves hackathons.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
  {
    name: "Rudra Sinha",
    email: "rudra.sinha@mail.com",
    password: "hashedpassword50",
    isVerified: true,
    walletBalance: getRandomAmount(200, 8000),
    totalDonated: 0,
    bio: "History, sports, learning new tech daily.",
    socials: { linkedin: "", twitter: "", instagram: "" },
    badges: [],
  },
];

async function seedUsers() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    const saltRounds = 10;
    const hashedUsers = await Promise.all(
      users.map(async (user) => ({
        ...user,
        password: await bcrypt.hash(user.password, saltRounds),
      }))
    );

    await User.deleteMany({});
    await User.insertMany(hashedUsers);

    console.log("Users seeded!");
  } catch (err) {
    console.error("Seed error:", err);
  } finally {
    mongoose.connection.close();
  }
}

seedUsers();
